### ISSUE TITLE
[Sesiones] Perdida de la sesión en el tutorial

### ISSUE THREAD

**Issue by A6MFlygon** [Rogarsu2014/JeR_Grupo_F#100]
## Prioridad
🟡 Medio
## Descripción
Al hacer Log In con una cuenta, si se entra a el tutorial se pierde la sesión y no se puede recuperar la sesión de nuevo haciendo Log In con la cuenta
 ## Pasos para reproducirlo
Hacer Log In -> Irse a Tutorial

**Comment by drowlerd** [comment]
Arreglada en #98
Razón: la escena a cargar no era la correcta
