### ISSUE TITLE
[Sesiones] Perdida de la sesión al volver al menú principal

### ISSUE THREAD

**Issue by A6MFlygon** [Rogarsu2014/JeR_Grupo_F#102]
## Prioridad
🟠 Alto
## Descripción
Al volver al menú principal desde la pantalla de victoria de Juego local, si se inició sesión, se pierde la sesión
 ## Pasos para reproducirlo
Hacer Log In -> Jugar en Local -> acabar la partida -> Volver al menú principal

**Comment by drowlerd** [comment]
Arreglada en #98
Razón: la escena a cargar no era la correcta
