### ISSUE TITLE
[Jugabilidad] No se puede saltar sobre otros jugadores

### ISSUE THREAD

**Issue by A6MFlygon** [Rogarsu2014/JeR_Grupo_F#103]
## Prioridad
🟠 Alto
## Descripción
En juego local cuando se inicia sesión al menos, no se puede saltar en otros jugadores cuando ya estás sobre uno
 ## Pasos para reproducirlo
Presionar la tecla de salto correspondiente estando sobre otro jugador

**Comment by drowlerd** [comment]
Arreglada en #116 
Razón: input no controlado correctamente
