### ISSUE TITLE
[Funcionalidad básica] No se puede acceder a la opción online

### ISSUE THREAD

**Issue by A6MFlygon** [Rogarsu2014/JeR_Grupo_F#104]
## Prioridad
🔴 Crítico
## Descripción
Una vez iniciada sesión, no permite acceder al menú de crear sala o unirse a sala
 ## Pasos para reproducirlo
Pasos en la descripición

**Comment by drowlerd** [comment]
Arreglada en #98
Razón: la escena a cargar no era la correcta
