### ISSUE TITLE
[Jugabilidad] Poco tiempo inicial

### ISSUE THREAD

**Issue by A6MFlygon** [Rogarsu2014/JeR_Grupo_F#105]
## Prioridad
🟢 Bajo
## Descripción
En la esena Cooperativa 3, 5 segundos son muy poco tiempo para que el jugador le de al botón incial en caso de estar despistado
 ## Pasos para reproducirlo
N/A

**Comment by drowlerd** [comment]
Razón: poco tiempo asignado
