### ISSUE TITLE
[Sesiones] Perdida de la sesión en créditos

### ISSUE THREAD

**Issue by A6MFlygon** [Rogarsu2014/JeR_Grupo_F#99]
## Prioridad
🟡 Medio
## Descripción
Al hacer Log In con una cuenta, si se entra a los créditos se pierde la sesión y no se puede recuperar la sesión de nuevo haciendo Log In con la cuenta
 ## Pasos para reproducirlo
Hacer Log In -> Irse a Créditos

**Comment by drowlerd** [comment]
Arreglada en #98
Razón: la escena a cargar no era la correcta
